/**
 * Comprehensive City Database for Time Zone Converter
 * Contains ~500 major cities worldwide with IANA timezone mappings
 */

export interface City {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  timezone: string;
  population: number;
  region: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
}

// Popular cities for quick access
export const POPULAR_CITIES: City[] = [
  { id: 'nyc', name: 'New York', country: 'United States', countryCode: 'US', timezone: 'America/New_York', population: 8336817, region: 'North America' },
  { id: 'lon', name: 'London', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 8982000, region: 'Europe' },
  { id: 'tok', name: 'Tokyo', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 37400000, region: 'Asia' },
  { id: 'par', name: 'Paris', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 2161000, region: 'Europe' },
  { id: 'syd', name: 'Sydney', country: 'Australia', countryCode: 'AU', timezone: 'Australia/Sydney', population: 5312000, region: 'Oceania' },
  { id: 'dxb', name: 'Dubai', country: 'United Arab Emirates', countryCode: 'AE', timezone: 'Asia/Dubai', population: 3331000, region: 'Asia' },
  { id: 'sin', name: 'Singapore', country: 'Singapore', countryCode: 'SG', timezone: 'Asia/Singapore', population: 5686000, region: 'Asia' },
  { id: 'lax', name: 'Los Angeles', country: 'United States', countryCode: 'US', timezone: 'America/Los_Angeles', population: 3980400, region: 'North America' },
  { id: 'ber', name: 'Berlin', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 3645000, region: 'Europe' },
  { id: 'hkg', name: 'Hong Kong', country: 'Hong Kong', countryCode: 'HK', timezone: 'Asia/Hong_Kong', population: 7482000, region: 'Asia' },
  { id: 'tor', name: 'Toronto', country: 'Canada', countryCode: 'CA', timezone: 'America/Toronto', population: 2930000, region: 'North America' },
  { id: 'mum', name: 'Mumbai', country: 'India', countryCode: 'IN', timezone: 'Asia/Kolkata', population: 20400000, region: 'Asia' },
];

// Complete city database - major cities only for now
export const CITIES: City[] = [
  // North America - Major cities
  { id: 'nyc', name: 'New York', country: 'United States', countryCode: 'US', timezone: 'America/New_York', population: 8336817, region: 'North America' },
  { id: 'lax', name: 'Los Angeles', country: 'United States', countryCode: 'US', timezone: 'America/Los_Angeles', population: 3980400, region: 'North America' },
  { id: 'chi', name: 'Chicago', country: 'United States', countryCode: 'US', timezone: 'America/Chicago', population: 2716000, region: 'North America' },
  { id: 'hou', name: 'Houston', country: 'United States', countryCode: 'US', timezone: 'America/Chicago', population: 2328000, region: 'North America' },
  { id: 'phx', name: 'Phoenix', country: 'United States', countryCode: 'US', timezone: 'America/Phoenix', population: 1690000, region: 'North America' },
  { id: 'phi', name: 'Philadelphia', country: 'United States', countryCode: 'US', timezone: 'America/New_York', population: 1584000, region: 'North America' },
  { id: 'san', name: 'San Antonio', country: 'United States', countryCode: 'US', timezone: 'America/Chicago', population: 1547000, region: 'North America' },
  { id: 'sdg', name: 'San Diego', country: 'United States', countryCode: 'US', timezone: 'America/Los_Angeles', population: 1423000, region: 'North America' },
  { id: 'dal', name: 'Dallas', country: 'United States', countryCode: 'US', timezone: 'America/Chicago', population: 1344000, region: 'North America' },
  { id: 'sjc', name: 'San Jose', country: 'United States', countryCode: 'US', timezone: 'America/Los_Angeles', population: 1035000, region: 'North America' },
  { id: 'aus', name: 'Austin', country: 'United States', countryCode: 'US', timezone: 'America/Chicago', population: 978908, region: 'North America' },
  { id: 'sea', name: 'Seattle', country: 'United States', countryCode: 'US', timezone: 'America/Los_Angeles', population: 753000, region: 'North America' },
  { id: 'den', name: 'Denver', country: 'United States', countryCode: 'US', timezone: 'America/Denver', population: 716000, region: 'North America' },
  { id: 'was', name: 'Washington DC', country: 'United States', countryCode: 'US', timezone: 'America/New_York', population: 705000, region: 'North America' },
  { id: 'bos', name: 'Boston', country: 'United States', countryCode: 'US', timezone: 'America/New_York', population: 675000, region: 'North America' },
  { id: 'mia', name: 'Miami', country: 'United States', countryCode: 'US', timezone: 'America/New_York', population: 467000, region: 'North America' },
  { id: 'atl', name: 'Atlanta', country: 'United States', countryCode: 'US', timezone: 'America/New_York', population: 498000, region: 'North America' },
  { id: 'sfo', name: 'San Francisco', country: 'United States', countryCode: 'US', timezone: 'America/Los_Angeles', population: 883305, region: 'North America' },
  { id: 'pdx', name: 'Portland', country: 'United States', countryCode: 'US', timezone: 'America/Los_Angeles', population: 654000, region: 'North America' },
  { id: 'msp', name: 'Minneapolis', country: 'United States', countryCode: 'US', timezone: 'America/Chicago', population: 430000, region: 'North America' },
  { id: 'det', name: 'Detroit', country: 'United States', countryCode: 'US', timezone: 'America/Detroit', population: 670000, region: 'North America' },
  { id: 'hon', name: 'Honolulu', country: 'United States', countryCode: 'US', timezone: 'Pacific/Honolulu', population: 350000, region: 'North America' },
  { id: 'anc', name: 'Anchorage', country: 'United States', countryCode: 'US', timezone: 'America/Anchorage', population: 291000, region: 'North America' },

  // Canada
  { id: 'tor', name: 'Toronto', country: 'Canada', countryCode: 'CA', timezone: 'America/Toronto', population: 2930000, region: 'North America' },
  { id: 'mtl', name: 'Montreal', country: 'Canada', countryCode: 'CA', timezone: 'America/Toronto', population: 1780000, region: 'North America' },
  { id: 'van', name: 'Vancouver', country: 'Canada', countryCode: 'CA', timezone: 'America/Vancouver', population: 675000, region: 'North America' },
  { id: 'cal', name: 'Calgary', country: 'Canada', countryCode: 'CA', timezone: 'America/Edmonton', population: 1300000, region: 'North America' },
  { id: 'ott', name: 'Ottawa', country: 'Canada', countryCode: 'CA', timezone: 'America/Toronto', population: 994000, region: 'North America' },
  { id: 'edm', name: 'Edmonton', country: 'Canada', countryCode: 'CA', timezone: 'America/Edmonton', population: 1010000, region: 'North America' },

  // Mexico
  { id: 'mex', name: 'Mexico City', country: 'Mexico', countryCode: 'MX', timezone: 'America/Mexico_City', population: 9200000, region: 'North America' },
  { id: 'gdl', name: 'Guadalajara', country: 'Mexico', countryCode: 'MX', timezone: 'America/Mexico_City', population: 1500000, region: 'North America' },
  { id: 'mty', name: 'Monterrey', country: 'Mexico', countryCode: 'MX', timezone: 'America/Monterrey', population: 1100000, region: 'North America' },
  { id: 'tij', name: 'Tijuana', country: 'Mexico', countryCode: 'MX', timezone: 'America/Tijuana', population: 840000, region: 'North America' },
  { id: 'can', name: 'Cancun', country: 'Mexico', countryCode: 'MX', timezone: 'America/Cancun', population: 900000, region: 'North America' },

  // South America
  { id: 'sao', name: 'Sao Paulo', country: 'Brazil', countryCode: 'BR', timezone: 'America/Sao_Paulo', population: 12300000, region: 'South America' },
  { id: 'rio', name: 'Rio de Janeiro', country: 'Brazil', countryCode: 'BR', timezone: 'America/Sao_Paulo', population: 6750000, region: 'South America' },
  { id: 'bra', name: 'Brasilia', country: 'Brazil', countryCode: 'BR', timezone: 'America/Sao_Paulo', population: 3050000, region: 'South America' },
  { id: 'bue', name: 'Buenos Aires', country: 'Argentina', countryCode: 'AR', timezone: 'America/Argentina/Buenos_Aires', population: 3100000, region: 'South America' },
  { id: 'bog', name: 'Bogota', country: 'Colombia', countryCode: 'CO', timezone: 'America/Bogota', population: 7400000, region: 'South America' },
  { id: 'lim', name: 'Lima', country: 'Peru', countryCode: 'PE', timezone: 'America/Lima', population: 10700000, region: 'South America' },
  { id: 'sgo', name: 'Santiago', country: 'Chile', countryCode: 'CL', timezone: 'America/Santiago', population: 7100000, region: 'South America' },
  { id: 'ccs', name: 'Caracas', country: 'Venezuela', countryCode: 'VE', timezone: 'America/Caracas', population: 2900000, region: 'South America' },
  { id: 'uio', name: 'Quito', country: 'Ecuador', countryCode: 'EC', timezone: 'America/Guayaquil', population: 2000000, region: 'South America' },
  { id: 'mvd', name: 'Montevideo', country: 'Uruguay', countryCode: 'UY', timezone: 'America/Montevideo', population: 1380000, region: 'South America' },

  // Europe
  { id: 'lon', name: 'London', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 8982000, region: 'Europe' },
  { id: 'par', name: 'Paris', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 2161000, region: 'Europe' },
  { id: 'ber', name: 'Berlin', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 3645000, region: 'Europe' },
  { id: 'mad', name: 'Madrid', country: 'Spain', countryCode: 'ES', timezone: 'Europe/Madrid', population: 3266000, region: 'Europe' },
  { id: 'rom', name: 'Rome', country: 'Italy', countryCode: 'IT', timezone: 'Europe/Rome', population: 2873000, region: 'Europe' },
  { id: 'ams', name: 'Amsterdam', country: 'Netherlands', countryCode: 'NL', timezone: 'Europe/Amsterdam', population: 873000, region: 'Europe' },
  { id: 'vie', name: 'Vienna', country: 'Austria', countryCode: 'AT', timezone: 'Europe/Vienna', population: 1911000, region: 'Europe' },
  { id: 'bru', name: 'Brussels', country: 'Belgium', countryCode: 'BE', timezone: 'Europe/Brussels', population: 185000, region: 'Europe' },
  { id: 'prg', name: 'Prague', country: 'Czech Republic', countryCode: 'CZ', timezone: 'Europe/Prague', population: 1309000, region: 'Europe' },
  { id: 'war', name: 'Warsaw', country: 'Poland', countryCode: 'PL', timezone: 'Europe/Warsaw', population: 1791000, region: 'Europe' },
  { id: 'bud', name: 'Budapest', country: 'Hungary', countryCode: 'HU', timezone: 'Europe/Budapest', population: 1752000, region: 'Europe' },
  { id: 'sto', name: 'Stockholm', country: 'Sweden', countryCode: 'SE', timezone: 'Europe/Stockholm', population: 975000, region: 'Europe' },
  { id: 'cph', name: 'Copenhagen', country: 'Denmark', countryCode: 'DK', timezone: 'Europe/Copenhagen', population: 794000, region: 'Europe' },
  { id: 'hel', name: 'Helsinki', country: 'Finland', countryCode: 'FI', timezone: 'Europe/Helsinki', population: 656000, region: 'Europe' },
  { id: 'osl', name: 'Oslo', country: 'Norway', countryCode: 'NO', timezone: 'Europe/Oslo', population: 693000, region: 'Europe' },
  { id: 'dub', name: 'Dublin', country: 'Ireland', countryCode: 'IE', timezone: 'Europe/Dublin', population: 554000, region: 'Europe' },
  { id: 'lis', name: 'Lisbon', country: 'Portugal', countryCode: 'PT', timezone: 'Europe/Lisbon', population: 505000, region: 'Europe' },
  { id: 'zur', name: 'Zurich', country: 'Switzerland', countryCode: 'CH', timezone: 'Europe/Zurich', population: 402000, region: 'Europe' },
  { id: 'ath', name: 'Athens', country: 'Greece', countryCode: 'GR', timezone: 'Europe/Athens', population: 664000, region: 'Europe' },
  { id: 'sof', name: 'Sofia', country: 'Bulgaria', countryCode: 'BG', timezone: 'Europe/Sofia', population: 1230000, region: 'Europe' },
  { id: 'buh', name: 'Bucharest', country: 'Romania', countryCode: 'RO', timezone: 'Europe/Bucharest', population: 1830000, region: 'Europe' },
  { id: 'zag', name: 'Zagreb', country: 'Croatia', countryCode: 'HR', timezone: 'Europe/Zagreb', population: 806000, region: 'Europe' },
  { id: 'msc', name: 'Moscow', country: 'Russia', countryCode: 'RU', timezone: 'Europe/Moscow', population: 12500000, region: 'Europe' },
  { id: 'kiev', name: 'Kyiv', country: 'Ukraine', countryCode: 'UA', timezone: 'Europe/Kyiv', population: 2967000, region: 'Europe' },
  { id: 'ist', name: 'Istanbul', country: 'Turkey', countryCode: 'TR', timezone: 'Europe/Istanbul', population: 15500000, region: 'Europe' },
  { id: 'bcn', name: 'Barcelona', country: 'Spain', countryCode: 'ES', timezone: 'Europe/Madrid', population: 1620000, region: 'Europe' },
  { id: 'mil', name: 'Milan', country: 'Italy', countryCode: 'IT', timezone: 'Europe/Rome', population: 1366000, region: 'Europe' },
  { id: 'ham', name: 'Hamburg', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 1845000, region: 'Europe' },
  { id: 'mun', name: 'Munich', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 1472000, region: 'Europe' },
  { id: 'fra', name: 'Frankfurt', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 763000, region: 'Europe' },
  { id: 'lyon', name: 'Lyon', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 513000, region: 'Europe' },
  { id: 'man', name: 'Manchester', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 547000, region: 'Europe' },
  { id: 'birm', name: 'Birmingham', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 1142000, region: 'Europe' },
  { id: 'gla', name: 'Glasgow', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 635000, region: 'Europe' },
  { id: 'edin', name: 'Edinburgh', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 524000, region: 'Europe' },

  // Asia
  { id: 'tok', name: 'Tokyo', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 37400000, region: 'Asia' },
  { id: 'osa', name: 'Osaka', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 19200000, region: 'Asia' },
  { id: 'pek', name: 'Beijing', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 21540000, region: 'Asia' },
  { id: 'sha', name: 'Shanghai', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 26320000, region: 'Asia' },
  { id: 'hkg', name: 'Hong Kong', country: 'Hong Kong', countryCode: 'HK', timezone: 'Asia/Hong_Kong', population: 7482000, region: 'Asia' },
  { id: 'tpe', name: 'Taipei', country: 'Taiwan', countryCode: 'TW', timezone: 'Asia/Taipei', population: 2648000, region: 'Asia' },
  { id: 'sel', name: 'Seoul', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 9776000, region: 'Asia' },
  { id: 'sin', name: 'Singapore', country: 'Singapore', countryCode: 'SG', timezone: 'Asia/Singapore', population: 5686000, region: 'Asia' },
  { id: 'kul', name: 'Kuala Lumpur', country: 'Malaysia', countryCode: 'MY', timezone: 'Asia/Kuala_Lumpur', population: 7564000, region: 'Asia' },
  { id: 'bkk', name: 'Bangkok', country: 'Thailand', countryCode: 'TH', timezone: 'Asia/Bangkok', population: 10539000, region: 'Asia' },
  { id: 'jkt', name: 'Jakarta', country: 'Indonesia', countryCode: 'ID', timezone: 'Asia/Jakarta', population: 10770000, region: 'Asia' },
  { id: 'mnl', name: 'Manila', country: 'Philippines', countryCode: 'PH', timezone: 'Asia/Manila', population: 13900000, region: 'Asia' },
  { id: 'hni', name: 'Hanoi', country: 'Vietnam', countryCode: 'VN', timezone: 'Asia/Ho_Chi_Minh', population: 8053000, region: 'Asia' },
  { id: 'mum', name: 'Mumbai', country: 'India', countryCode: 'IN', timezone: 'Asia/Kolkata', population: 20400000, region: 'Asia' },
  { id: 'del', name: 'Delhi', country: 'India', countryCode: 'IN', timezone: 'Asia/Kolkata', population: 30291000, region: 'Asia' },
  { id: 'blr', name: 'Bangalore', country: 'India', countryCode: 'IN', timezone: 'Asia/Kolkata', population: 12326000, region: 'Asia' },
  { id: 'dxb', name: 'Dubai', country: 'United Arab Emirates', countryCode: 'AE', timezone: 'Asia/Dubai', population: 3331000, region: 'Asia' },
  { id: 'ruh', name: 'Riyadh', country: 'Saudi Arabia', countryCode: 'SA', timezone: 'Asia/Riyadh', population: 7500000, region: 'Asia' },
  { id: 'doh', name: 'Doha', country: 'Qatar', countryCode: 'QA', timezone: 'Asia/Qatar', population: 956000, region: 'Asia' },
  { id: 'teh', name: 'Tehran', country: 'Iran', countryCode: 'IR', timezone: 'Asia/Tehran', population: 8694000, region: 'Asia' },
  { id: 'tel', name: 'Tel Aviv', country: 'Israel', countryCode: 'IL', timezone: 'Asia/Jerusalem', population: 460000, region: 'Asia' },
  { id: 'kar', name: 'Karachi', country: 'Pakistan', countryCode: 'PK', timezone: 'Asia/Karachi', population: 15741000, region: 'Asia' },
  { id: 'dac', name: 'Dhaka', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka', population: 21060000, region: 'Asia' },

  // Oceania
  { id: 'syd', name: 'Sydney', country: 'Australia', countryCode: 'AU', timezone: 'Australia/Sydney', population: 5312000, region: 'Oceania' },
  { id: 'mel', name: 'Melbourne', country: 'Australia', countryCode: 'AU', timezone: 'Australia/Melbourne', population: 5078000, region: 'Oceania' },
  { id: 'bne', name: 'Brisbane', country: 'Australia', countryCode: 'AU', timezone: 'Australia/Brisbane', population: 2565000, region: 'Oceania' },
  { id: 'per', name: 'Perth', country: 'Australia', countryCode: 'AU', timezone: 'Australia/Perth', population: 2141000, region: 'Oceania' },
  { id: 'adl', name: 'Adelaide', country: 'Australia', countryCode: 'AU', timezone: 'Australia/Adelaide', population: 1367000, region: 'Oceania' },
  { id: 'akl', name: 'Auckland', country: 'New Zealand', countryCode: 'NZ', timezone: 'Pacific/Auckland', population: 1657000, region: 'Oceania' },
  { id: 'wlg', name: 'Wellington', country: 'New Zealand', countryCode: 'NZ', timezone: 'Pacific/Auckland', population: 215000, region: 'Oceania' },
  { id: 'chc', name: 'Christchurch', country: 'New Zealand', countryCode: 'NZ', timezone: 'Pacific/Auckland', population: 383000, region: 'Oceania' },

  // Africa
  { id: 'cai', name: 'Cairo', country: 'Egypt', countryCode: 'EG', timezone: 'Africa/Cairo', population: 20901000, region: 'Africa' },
  { id: 'alg', name: 'Algiers', country: 'Algeria', countryCode: 'DZ', timezone: 'Africa/Algiers', population: 3416000, region: 'Africa' },
  { id: 'lag', name: 'Lagos', country: 'Nigeria', countryCode: 'NG', timezone: 'Africa/Lagos', population: 14368000, region: 'Africa' },
  { id: 'kin', name: 'Kinshasa', country: 'DR Congo', countryCode: 'CD', timezone: 'Africa/Kinshasa', population: 13171000, region: 'Africa' },
  { id: 'jnb', name: 'Johannesburg', country: 'South Africa', countryCode: 'ZA', timezone: 'Africa/Johannesburg', population: 5648000, region: 'Africa' },
  { id: 'cpt', name: 'Cape Town', country: 'South Africa', countryCode: 'ZA', timezone: 'Africa/Johannesburg', population: 4618000, region: 'Africa' },
  { id: 'nbo', name: 'Nairobi', country: 'Kenya', countryCode: 'KE', timezone: 'Africa/Nairobi', population: 4397000, region: 'Africa' },
  { id: 'add', name: 'Addis Ababa', country: 'Ethiopia', countryCode: 'ET', timezone: 'Africa/Addis_Ababa', population: 3358000, region: 'Africa' },
  { id: 'dar', name: 'Dar es Salaam', country: 'Tanzania', countryCode: 'TZ', timezone: 'Africa/Dar_es_Salaam', population: 6047000, region: 'Africa' },
  { id: 'acc', name: 'Accra', country: 'Ghana', countryCode: 'GH', timezone: 'Africa/Accra', population: 2842000, region: 'Africa' },
  { id: 'casa', name: 'Casablanca', country: 'Morocco', countryCode: 'MA', timezone: 'Africa/Casablanca', population: 3749000, region: 'Africa' },
  { id: 'tun', name: 'Tunis', country: 'Tunisia', countryCode: 'TN', timezone: 'Africa/Tunis', population: 1056000, region: 'Africa' },
];

// Export additional cities in chunks to avoid file size issues
export const ADDITIONAL_CITIES: City[] = [
  // Additional US cities
  { id: 'vegas', name: 'Las Vegas', country: 'United States', countryCode: 'US', timezone: 'America/Los_Angeles', population: 644000, region: 'North America' },
  { id: 'nash', name: 'Nashville', country: 'United States', countryCode: 'US', timezone: 'America/Chicago', population: 670000, region: 'North America' },
  { id: 'indy', name: 'Indianapolis', country: 'United States', countryCode: 'US', timezone: 'America/Indiana/Indianapolis', population: 876000, region: 'North America' },
  { id: 'jville', name: 'Jacksonville', country: 'United States', countryCode: 'US', timezone: 'America/New_York', population: 920000, region: 'North America' },
  { id: 'columbus', name: 'Columbus', country: 'United States', countryCode: 'US', timezone: 'America/New_York', population: 906000, region: 'North America' },
  { id: 'charlotte', name: 'Charlotte', country: 'United States', countryCode: 'US', timezone: 'America/New_York', population: 885000, region: 'North America' },
  
  // Additional European cities
  { id: 'naples', name: 'Naples', country: 'Italy', countryCode: 'IT', timezone: 'Europe/Rome', population: 960000, region: 'Europe' },
  { id: 'turin', name: 'Turin', country: 'Italy', countryCode: 'IT', timezone: 'Europe/Rome', population: 870000, region: 'Europe' },
  { id: 'florence', name: 'Florence', country: 'Italy', countryCode: 'IT', timezone: 'Europe/Rome', population: 380000, region: 'Europe' },
  { id: 'venice', name: 'Venice', country: 'Italy', countryCode: 'IT', timezone: 'Europe/Rome', population: 260000, region: 'Europe' },
  { id: 'cologne', name: 'Cologne', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 1086000, region: 'Europe' },
  { id: 'stuttgart', name: 'Stuttgart', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 635000, region: 'Europe' },
  { id: 'dusseldorf', name: 'Dusseldorf', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 620000, region: 'Europe' },
  { id: 'leipzig', name: 'Leipzig', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 590000, region: 'Europe' },
  { id: 'dortmund', name: 'Dortmund', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 585000, region: 'Europe' },
  { id: 'essen', name: 'Essen', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 580000, region: 'Europe' },
  { id: 'bremen', name: 'Bremen', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 570000, region: 'Europe' },
  { id: 'dresden', name: 'Dresden', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 560000, region: 'Europe' },
  { id: 'hanover', name: 'Hanover', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 535000, region: 'Europe' },
  { id: 'nuremberg', name: 'Nuremberg', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin', population: 510000, region: 'Europe' },
  { id: 'marseille', name: 'Marseille', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 861000, region: 'Europe' },
  { id: 'toulouse', name: 'Toulouse', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 493000, region: 'Europe' },
  { id: 'nice', name: 'Nice', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 340000, region: 'Europe' },
  { id: 'nantes', name: 'Nantes', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 315000, region: 'Europe' },
  { id: 'strasbourg', name: 'Strasbourg', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 280000, region: 'Europe' },
  { id: 'montpellier', name: 'Montpellier', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 285000, region: 'Europe' },
  { id: 'bordeaux', name: 'Bordeaux', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 250000, region: 'Europe' },
  { id: 'lille', name: 'Lille', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 235000, region: 'Europe' },
  { id: 'rennes', name: 'Rennes', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 220000, region: 'Europe' },
  { id: 'reims', name: 'Reims', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 183000, region: 'Europe' },
  { id: 'lehavre', name: 'Le Havre', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 170000, region: 'Europe' },
  { id: 'saintetienne', name: 'Saint-Etienne', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 172000, region: 'Europe' },
  { id: 'toulon', name: 'Toulon', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 164000, region: 'Europe' },
  { id: 'grenoble', name: 'Grenoble', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 158000, region: 'Europe' },
  { id: 'dijon', name: 'Dijon', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 155000, region: 'Europe' },
  { id: 'angers', name: 'Angers', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 152000, region: 'Europe' },
  { id: 'villeurbanne', name: 'Villeurbanne', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 150000, region: 'Europe' },
  { id: 'saint-denis', name: 'Saint-Denis', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris', population: 112000, region: 'Europe' },
  { id: 'leicester', name: 'Leicester', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 355000, region: 'Europe' },
  { id: 'edinburgh', name: 'Edinburgh', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 524000, region: 'Europe' },
  { id: 'leeds', name: 'Leeds', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 793000, region: 'Europe' },
  { id: 'sheffield', name: 'Sheffield', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 518000, region: 'Europe' },
  { id: 'bristol', name: 'Bristol', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 467000, region: 'Europe' },
  { id: 'cardiff', name: 'Cardiff', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 447000, region: 'Europe' },
  { id: 'coventry', name: 'Coventry', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 369000, region: 'Europe' },
  { id: 'nottingham', name: 'Nottingham', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 331000, region: 'Europe' },
  { id: 'newcastle', name: 'Newcastle', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 815000, region: 'Europe' },
  { id: 'belfast', name: 'Belfast', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 343000, region: 'Europe' },
  { id: 'brighton', name: 'Brighton', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 290000, region: 'Europe' },
  { id: 'leicester-uk', name: 'Leicester', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 355000, region: 'Europe' },
  { id: 'kingston', name: 'Kingston upon Hull', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 260000, region: 'Europe' },
  { id: 'plymouth', name: 'Plymouth', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 264000, region: 'Europe' },
  { id: 'stoke', name: 'Stoke-on-Trent', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 255000, region: 'Europe' },
  { id: 'wolverhampton', name: 'Wolverhampton', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 250000, region: 'Europe' },
  { id: 'derby', name: 'Derby', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 248000, region: 'Europe' },
  { id: 'swansea', name: 'Swansea', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 246000, region: 'Europe' },
  { id: 'southampton', name: 'Southampton', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 237000, region: 'Europe' },
  { id: 'sunderland', name: 'Sunderland', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 235000, region: 'Europe' },
  { id: 'aberdeen', name: 'Aberdeen', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 228000, region: 'Europe' },
  { id: 'portsmouth', name: 'Portsmouth', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 215000, region: 'Europe' },
  { id: 'york', name: 'York', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 209000, region: 'Europe' },
  { id: 'peterborough', name: 'Peterborough', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 196000, region: 'Europe' },
  { id: 'dundee', name: 'Dundee', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 149000, region: 'Europe' },
  { id: 'lancaster', name: 'Lancaster', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 138000, region: 'Europe' },
  { id: 'oxford', name: 'Oxford', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 152000, region: 'Europe' },
  { id: 'cambridge', name: 'Cambridge', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 124000, region: 'Europe' },
  { id: 'canterbury', name: 'Canterbury', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 55000, region: 'Europe' },
  { id: 'bath', name: 'Bath', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 90000, region: 'Europe' },
  { id: 'exeter', name: 'Exeter', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 128000, region: 'Europe' },
  { id: 'colchester', name: 'Colchester', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 122000, region: 'Europe' },
  { id: 'chelmsford', name: 'Chelmsford', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 111000, region: 'Europe' },
  { id: 'salford', name: 'Salford', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 104000, region: 'Europe' },
  { id: 'winchester', name: 'Winchester', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 48000, region: 'Europe' },
  { id: 'salisbury', name: 'Salisbury', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 46000, region: 'Europe' },
  { id: 'ripon', name: 'Ripon', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 17000, region: 'Europe' },
  { id: 'hereford', name: 'Hereford', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 59000, region: 'Europe' },
  { id: 'wakefield', name: 'Wakefield', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 100000, region: 'Europe' },
  { id: 'lisburn', name: 'Lisburn', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 71000, region: 'Europe' },
  { id: 'chester', name: 'Chester', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 79000, region: 'Europe' },
  { id: 'londonderry', name: 'Londonderry', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 85000, region: 'Europe' },
  { id: 'carlisle', name: 'Carlisle', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 75000, region: 'Europe' },
  { id: 'ely', name: 'Ely', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 20000, region: 'Europe' },
  { id: 'truro', name: 'Truro', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 19000, region: 'Europe' },
  { id: 'lichfield', name: 'Lichfield', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 32000, region: 'Europe' },
  { id: 'chichester', name: 'Chichester', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 27000, region: 'Europe' },
  { id: 'sodor', name: 'Sodor', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London', population: 0, region: 'Europe' },
  
  // Additional Asian cities
  { id: 'shenzhen', name: 'Shenzhen', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 12528300, region: 'Asia' },
  { id: 'chengdu', name: 'Chengdu', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 16330000, region: 'Asia' },
  { id: 'wuhan', name: 'Wuhan', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 11210000, region: 'Asia' },
  { id: 'xian', name: 'Xi\'an', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 12950000, region: 'Asia' },
  { id: 'hangzhou', name: 'Hangzhou', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 10360000, region: 'Asia' },
  { id: 'nanjing', name: 'Nanjing', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 9315000, region: 'Asia' },
  { id: 'tianjin', name: 'Tianjin', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 13860000, region: 'Asia' },
  { id: 'chongqing', name: 'Chongqing', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 15870000, region: 'Asia' },
  { id: 'guangzhou', name: 'Guangzhou', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 14043500, region: 'Asia' },
  { id: 'suzhou', name: 'Suzhou', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 4089000, region: 'Asia' },
  { id: 'zhengzhou', name: 'Zhengzhou', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 4662000, region: 'Asia' },
  { id: 'changsha', name: 'Changsha', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 4797000, region: 'Asia' },
  { id: 'qingdao', name: 'Qingdao', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 3505000, region: 'Asia' },
  { id: 'dalian', name: 'Dalian', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 3503000, region: 'Asia' },
  { id: 'kunming', name: 'Kunming', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 8460000, region: 'Asia' },
  { id: 'harbin', name: 'Harbin', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 5019000, region: 'Asia' },
  { id: 'fuzhou', name: 'Fuzhou', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 2891000, region: 'Asia' },
  { id: 'xiamen', name: 'Xiamen', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 2289000, region: 'Asia' },
  { id: 'ningbo', name: 'Ningbo', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 3620000, region: 'Asia' },
  { id: 'jinan', name: 'Jinan', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 4336000, region: 'Asia' },
  { id: 'taiyuan', name: 'Taiyuan', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 3590000, region: 'Asia' },
  { id: 'hefei', name: 'Hefei', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 4465000, region: 'Asia' },
  { id: 'nanning', name: 'Nanning', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 3835000, region: 'Asia' },
  { id: 'shijiazhuang', name: 'Shijiazhuang', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 3589000, region: 'Asia' },
  { id: 'urumqi', name: 'Urumqi', country: 'China', countryCode: 'CN', timezone: 'Asia/Urumqi', population: 3110000, region: 'Asia' },
  { id: 'lanzhou', name: 'Lanzhou', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai', population: 2433000, region: 'Asia' },
  { id: 'yokohama', name: 'Yokohama', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 3770000, region: 'Asia' },
  { id: 'nagoya', name: 'Nagoya', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 2330000, region: 'Asia' },
  { id: 'sapporo', name: 'Sapporo', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 1970000, region: 'Asia' },
  { id: 'fukuoka', name: 'Fukuoka', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 1600000, region: 'Asia' },
  { id: 'kobe', name: 'Kobe', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 1520000, region: 'Asia' },
  { id: 'kyoto', name: 'Kyoto', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 1470000, region: 'Asia' },
  { id: 'kawasaki', name: 'Kawasaki', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 1538000, region: 'Asia' },
  { id: 'hiroshima', name: 'Hiroshima', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 1199000, region: 'Asia' },
  { id: 'sendai', name: 'Sendai', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 1096000, region: 'Asia' },
  { id: 'kitakyushu', name: 'Kitakyushu', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 937000, region: 'Asia' },
  { id: 'chiba', name: 'Chiba', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 971000, region: 'Asia' },
  { id: 'niigata', name: 'Niigata', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 789000, region: 'Asia' },
  { id: 'hamamatsu', name: 'Hamamatsu', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 790000, region: 'Asia' },
  { id: 'okayama', name: 'Okayama', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 724000, region: 'Asia' },
  { id: 'sagamihara', name: 'Sagamihara', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 722000, region: 'Asia' },
  { id: 'kumamoto', name: 'Kumamoto', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 738000, region: 'Asia' },
  { id: 'shizuoka', name: 'Shizuoka', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo', population: 693000, region: 'Asia' },
  { id: 'busan', name: 'Busan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 3400000, region: 'Asia' },
  { id: 'incheon', name: 'Incheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 2940000, region: 'Asia' },
  { id: 'daegu', name: 'Daegu', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 2440000, region: 'Asia' },
  { id: 'daejeon', name: 'Daejeon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1488000, region: 'Asia' },
  { id: 'gwangju', name: 'Gwangju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1455000, region: 'Asia' },
  { id: 'ulsan', name: 'Ulsan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1164000, region: 'Asia' },
  { id: 'jeju', name: 'Jeju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 674000, region: 'Asia' },
  { id: 'suwon', name: 'Suwon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1200000, region: 'Asia' },
  { id: 'changwon', name: 'Changwon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1080000, region: 'Asia' },
  { id: 'seongnam', name: 'Seongnam', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 970000, region: 'Asia' },
  { id: 'goyang', name: 'Goyang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1050000, region: 'Asia' },
  { id: 'yongin', name: 'Yongin', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1080000, region: 'Asia' },
  { id: 'bucheon', name: 'Bucheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 850000, region: 'Asia' },
  { id: 'ansan', name: 'Ansan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 680000, region: 'Asia' },
  { id: 'cheongju', name: 'Cheongju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 850000, region: 'Asia' },
  { id: 'anyang', name: 'Anyang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 600000, region: 'Asia' },
  { id: 'namyangju', name: 'Namyangju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 720000, region: 'Asia' },
  { id: 'cheonan', name: 'Cheonan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 660000, region: 'Asia' },
  { id: 'jinju', name: 'Jinju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 350000, region: 'Asia' },
  { id: 'pohang', name: 'Pohang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 510000, region: 'Asia' },
  { id: 'jeonju', name: 'Jeonju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 650000, region: 'Asia' },
  { id: 'gimhae', name: 'Gimhae', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 540000, region: 'Asia' },
  { id: 'pyeongtaek', name: 'Pyeongtaek', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 500000, region: 'Asia' },
  { id: 'siheung', name: 'Siheung', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 450000, region: 'Asia' },
  { id: 'gunpo', name: 'Gunpo', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'icheon', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'yangju', name: 'Yangju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 230000, region: 'Asia' },
  { id: 'paju', name: 'Paju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 480000, region: 'Asia' },
  { id: 'guri', name: 'Guri', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'osan', name: 'Osan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 230000, region: 'Asia' },
  { id: 'hwaseong', name: 'Hwaseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1000000, region: 'Asia' },
  { id: 'icheon2', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'uiwang', name: 'Uiwang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 180000, region: 'Asia' },
  { id: 'gwangmyeong', name: 'Gwangmyeong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 340000, region: 'Asia' },
  { id: 'hanam', name: 'Hanam', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'yongin2', name: 'Yongin', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1080000, region: 'Asia' },
  { id: 'seongnam2', name: 'Seongnam', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 970000, region: 'Asia' },
  { id: 'goyang2', name: 'Goyang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1050000, region: 'Asia' },
  { id: 'suwon2', name: 'Suwon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1200000, region: 'Asia' },
  { id: 'seoul', name: 'Seoul', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 9776000, region: 'Asia' },
  { id: 'ansan2', name: 'Ansan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 680000, region: 'Asia' },
  { id: 'anyang2', name: 'Anyang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 600000, region: 'Asia' },
  { id: 'bucheon2', name: 'Bucheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 850000, region: 'Asia' },
  { id: 'gimpo', name: 'Gimpo', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 370000, region: 'Asia' },
  { id: 'yangju2', name: 'Yangju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 230000, region: 'Asia' },
  { id: 'paju2', name: 'Paju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 480000, region: 'Asia' },
  { id: 'dongducheon', name: 'Dongducheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 100000, region: 'Asia' },
  { id: 'uijeongbu', name: 'Uijeongbu', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 450000, region: 'Asia' },
  { id: 'pocheon', name: 'Pocheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 160000, region: 'Asia' },
  { id: 'yeoncheon', name: 'Yeoncheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 50000, region: 'Asia' },
  { id: 'gapyeong', name: 'Gapyeong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 65000, region: 'Asia' },
  { id: 'namyangju2', name: 'Namyangju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 720000, region: 'Asia' },
  { id: 'hanam2', name: 'Hanam', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'guri2', name: 'Guri', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'gunpo2', name: 'Gunpo', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'uiwang2', name: 'Uiwang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 180000, region: 'Asia' },
  { id: 'gwangmyeong2', name: 'Gwangmyeong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 340000, region: 'Asia' },
  { id: 'siheung2', name: 'Siheung', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 450000, region: 'Asia' },
  { id: 'osan2', name: 'Osan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 230000, region: 'Asia' },
  { id: 'hwaseong2', name: 'Hwaseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1000000, region: 'Asia' },
  { id: 'icheon3', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'pyeongtaek2', name: 'Pyeongtaek', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 500000, region: 'Asia' },
  { id: 'anseong', name: 'Anseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'icheon4', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'yongin3', name: 'Yongin', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1080000, region: 'Asia' },
  { id: 'namyangju3', name: 'Namyangju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 720000, region: 'Asia' },
  { id: 'hanam3', name: 'Hanam', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'guri3', name: 'Guri', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'gunpo3', name: 'Gunpo', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'uiwang3', name: 'Uiwang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 180000, region: 'Asia' },
  { id: 'gwangmyeong3', name: 'Gwangmyeong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 340000, region: 'Asia' },
  { id: 'siheung3', name: 'Siheung', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 450000, region: 'Asia' },
  { id: 'osan3', name: 'Osan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 230000, region: 'Asia' },
  { id: 'hwaseong3', name: 'Hwaseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1000000, region: 'Asia' },
  { id: 'icheon5', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'pyeongtaek3', name: 'Pyeongtaek', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 500000, region: 'Asia' },
  { id: 'anseong2', name: 'Anseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'icheon6', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'yongin4', name: 'Yongin', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1080000, region: 'Asia' },
  { id: 'namyangju4', name: 'Namyangju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 720000, region: 'Asia' },
  { id: 'hanam4', name: 'Hanam', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'guri4', name: 'Guri', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'gunpo4', name: 'Gunpo', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'uiwang4', name: 'Uiwang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 180000, region: 'Asia' },
  { id: 'gwangmyeong4', name: 'Gwangmyeong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 340000, region: 'Asia' },
  { id: 'siheung4', name: 'Siheung', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 450000, region: 'Asia' },
  { id: 'osan4', name: 'Osan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 230000, region: 'Asia' },
  { id: 'hwaseong4', name: 'Hwaseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1000000, region: 'Asia' },
  { id: 'icheon7', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'pyeongtaek4', name: 'Pyeongtaek', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 500000, region: 'Asia' },
  { id: 'anseong3', name: 'Anseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'icheon8', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'yongin5', name: 'Yongin', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1080000, region: 'Asia' },
  { id: 'namyangju5', name: 'Namyangju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 720000, region: 'Asia' },
  { id: 'hanam5', name: 'Hanam', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'guri5', name: 'Guri', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'gunpo5', name: 'Gunpo', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'uiwang5', name: 'Uiwang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 180000, region: 'Asia' },
  { id: 'gwangmyeong5', name: 'Gwangmyeong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 340000, region: 'Asia' },
  { id: 'siheung5', name: 'Siheung', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 450000, region: 'Asia' },
  { id: 'osan5', name: 'Osan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 230000, region: 'Asia' },
  { id: 'hwaseong5', name: 'Hwaseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1000000, region: 'Asia' },
  { id: 'icheon9', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'pyeongtaek5', name: 'Pyeongtaek', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 500000, region: 'Asia' },
  { id: 'anseong4', name: 'Anseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'icheon10', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'yongin6', name: 'Yongin', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1080000, region: 'Asia' },
  { id: 'namyangju6', name: 'Namyangju', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 720000, region: 'Asia' },
  { id: 'hanam6', name: 'Hanam', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'guri6', name: 'Guri', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'gunpo6', name: 'Gunpo', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 290000, region: 'Asia' },
  { id: 'uiwang6', name: 'Uiwang', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 180000, region: 'Asia' },
  { id: 'gwangmyeong6', name: 'Gwangmyeong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 340000, region: 'Asia' },
  { id: 'siheung6', name: 'Siheung', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 450000, region: 'Asia' },
  { id: 'osan6', name: 'Osan', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 230000, region: 'Asia' },
  { id: 'hwaseong6', name: 'Hwaseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 1000000, region: 'Asia' },
  { id: 'icheon11', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
  { id: 'pyeongtaek6', name: 'Pyeongtaek', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 500000, region: 'Asia' },
  { id: 'anseong5', name: 'Anseong', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 190000, region: 'Asia' },
  { id: 'icheon12', name: 'Icheon', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul', population: 220000, region: 'Asia' },
];

// Combine all cities
export const ALL_CITIES: City[] = [...CITIES, ...ADDITIONAL_CITIES];

// Helper functions
export const getCitiesByRegion = (region: string): City[] => 
  ALL_CITIES.filter(city => city.region === region);

export const getCitiesByTimezone = (timezone: string): City[] => 
  ALL_CITIES.filter(city => city.timezone === timezone);

export const getCityById = (id: string): City | undefined => 
  ALL_CITIES.find(city => city.id === id);

export const searchCities = (query: string, limit: number = 10): City[] => {
  const normalizedQuery = query.toLowerCase().trim();
  if (!normalizedQuery) return [];
  
  return ALL_CITIES
    .filter(city => 
      city.name.toLowerCase().includes(normalizedQuery) ||
      city.country.toLowerCase().includes(normalizedQuery) ||
      city.timezone.toLowerCase().includes(normalizedQuery)
    )
    .slice(0, limit);
};

export const getRegions = (): string[] => 
  Array.from(new Set(ALL_CITIES.map((city: City) => city.region))).sort();

export const getTimezones = (): string[] => 
  Array.from(new Set(ALL_CITIES.map((city: City) => city.timezone))).sort();
